### ISSUE TITLE
module.json: Change "author" to "authors"

### ISSUE THREAD

**Issue by gfactor** [Drental/foundryvtt-pf2e-f-is-for-flatfooted#13]
Very minor issue: Foundry throws a warning about the "author" attribute. It's been replaced with "authors", and the structure of this new attribute is in the Module Development article (under "Optional Manifest Attributes") on the Foundry VTT site. The next time you update module.json, can you also change to using "authors"?

**Comment by ksignorini** [comment]
Weirdest thing... in my copy it _does_ say "authors" but it's still throwing the same warning.

![image](https://user-images.githubusercontent.com/6867660/215305630-06720182-2a90-47b3-b8e4-8e17035b1639.png)

Any ideas on how to fix this?

**Comment by Drental** [comment]
okay. done.
