### ISSUE TITLE
feature request: please add avoid notice toggle

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [Drental/foundryvtt-pf2e-f-is-for-flatfooted#14]
i love this mod but i didnt see an avoid notice. my players use that alot and id love to get a keybind toggle. many thanks!

**Comment by Drental** [comment]
there is no useful way to link this module to avoid notice.
![image](https://user-images.githubusercontent.com/74384067/205849674-936ee3e6-1c85-4f1a-9a37-430f00596cae.png)
the System doesn't have a condition or even an effect for it.

**Comment by ThingsCouldGetDicey** [comment]
you could have it to roll the stealth check like sneak but with the avoid notice chat card. that could be useful.

**Comment by Drental** [comment]
oh, I just saw that the actions are in the module but not auto generated. I'll look into it.

**Comment by Drental** [comment]
added the macro in theory with update 4.20
