### ISSUE TITLE
End Turn lets anyone advance combat turn

### ISSUE THREAD

**Issue by JamzTheMan** [Drental/foundryvtt-pf2e-f-is-for-flatfooted#15]
Although it says as GM this will end anyone's turn, I find that any player can advance anyone's turn with this keybind.

![image](https://user-images.githubusercontent.com/8051654/208744537-6e6f45bc-7d77-4d09-be66-0a0096182d28.png)

(retested with no other modules)

> Foundry Virtual Tabletop: Version 10, 10.291
> Game System: pf2e, 4.5.1
> Active Modules: 1
> Performance Mode: 2
> 
> OS: Unknown
> Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54
> GPU: ANGLE (NVIDIA, NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0, D3D11)
> Max Texture Size: 16384
> 
> Scene: 6000 x 4600 | Grid Size: 100 | Padding Percentage: 0.25
> Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 20
> 
> Actors: 13 | Items: 46 | Journal: 108 | Rollable Tables: 0 |
> Playlists: 0 | Compendium Packs: 73 | Chat Messages: 58

**Comment by Drental** [comment]
oh, uh.
This seems to me like it should be a permission issue
I'll ask if this is intended and update the description depending on what the foundry people say.

**Comment by Drental** [comment]
fixed.
