### ISSUE TITLE
Error applying offguard 

### ISSUE THREAD

**Issue by AKCarter07** [Drental/foundryvtt-pf2e-f-is-for-flatfooted#23]
Foundry 11.307
Pathfinder 5.3.0
Keybind Menagerie 5.3.1

On using F for flat footed, getting error:
Uncaught (in promise) Error: PF2e System | Unrecognized condition: offguard
    at ErrorPF2e (pf2e.mjs:1:40717)
    at _ActorPF2e2.toggleCondition (pf2e.mjs:28:183159)
    at Object.onDown (index.js:104:49)
    at KeyboardManager._executeKeybind (foundry.js:2500:66)
    at KeyboardManager._processKeyboardContext (foundry.js:2541:33)
    at KeyboardManager._handleKeyboardEvent (foundry.js:2599:10)
    at foundry.js:2225:54

**Comment by Drental** [comment]
this is not the latest version of the module.

**Comment by AKCarter07** [comment]
Apologies. I thought it was because I had just reinstalled the module.

**Comment by lafflam** [comment]
As of 2023-12-01, the most up-to-date available through the FoundryVTT add-on modules library is still 5.3.1. Is there a way to update the Foundry library to officially point to 5.3.2? Not everyone is going to know they can manually install from https://github.com/Drental/foundryvtt-pf2e-f-is-for-flatfooted/releases/download/5.3.2/module.json

**Comment by Drental** [comment]
Oh, right, done
