### ISSUE TITLE
Show Token Art Not Working

### ISSUE THREAD

**Issue by KazOokami** [Drental/foundryvtt-pf2e-f-is-for-flatfooted#24]
Show Token Art doesn't work. I´ve tried with all other modules deactivated and checked if the other keybinds was working, also tried changing the keys. Apparently the problem is just with Show Token Art.

**Comment by rdbell1** [comment]
Create a Diversion is also not working

**Comment by git-kor-av** [comment]
> Show Token Art doesn't work. I´ve tried with all other modules deactivated and checked if the other keybinds was working, also tried changing the keys. Apparently the problem is just with Show Token Art.

Can confirm that this is not working properly.  The following error is seen in the console:
![image](https://github.com/Drental/foundryvtt-pf2e-f-is-for-flatfooted/assets/32276185/cb1eeec6-a299-450d-b106-6ed171e3c190)
