### ISSUE TITLE
Where is the list of keybinds?

### ISSUE THREAD

**Issue by ksignorini** [Drental/foundryvtt-pf2e-f-is-for-flatfooted#26]
Can the keybinds be configured?

Where is the list of keybinds?

**Comment by Drental** [comment]
Hello,

sorry to get back to you this late.

The Keybinds are managed by foundry, you can find them in the "Configure Controls" menu in the sidebar

![image](https://github.com/Drental/foundryvtt-pf2e-f-is-for-flatfooted/assets/74384067/2df046d1-5dab-43ea-b9c2-1f3ba28f7472)
