### ISSUE TITLE
Closing Cover pop-up still applies a status

### ISSUE THREAD

**Issue by jocolamarco** [Drental/foundryvtt-pf2e-f-is-for-flatfooted#7]
1. Select a Token and activate the cover shortcut
2. Click "Close" on the Pop-up  
3. Notice how a standard cover is applied and a toast notification states that "no selection was made: cover is inactive"

![imagem](https://user-images.githubusercontent.com/45291719/151980107-57b9e709-778d-4252-bb9c-e0cd6d8db6a6.png)

![imagem](https://user-images.githubusercontent.com/45291719/151980200-2aa6b830-0839-46e7-8c07-c8dcd2455f10.png)

Core Version: 9.245

System: pf2e 3.3.1.10273 (The PF2e System Developers) 

pf2e-f-is-for-flatfooted 3.3.2 (DrentalBot <drentalbot@crumblinggiant.com>)

**Comment by Drental** [comment]
that is core behavior of trying to addd an effect with a choice set. The module has done all its code before that dialog appears.
